/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_redbaby_utils_FileUtil */

#ifndef _Included_com_example_redbaby_utils_FileUtil
#define _Included_com_example_redbaby_utils_FileUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_redbaby_utils_FileUtil
 * Method:    getFileAccessTime
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_redbaby_utils_FileUtil_getFileAccessTime
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_example_redbaby_utils_FileUtil
 * Method:    howmanyTimeUnAccess
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_redbaby_utils_FileUtil_howmanyTimeUnAccess
  (JNIEnv *, jclass, jstring);


/*
 * Class:     com_example_redbaby_utils_FileUtil
 * Method:    data
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_example_redbaby_utils_FileUtil_data
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
