/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloworldformc_MainActivity */

#ifndef _Included_com_example_helloworldformc_MainActivity
#define _Included_com_example_helloworldformc_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloworldformc_MainActivity
 * Method:    helloWorldFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloworldformc_MainActivity_helloWorldFromC
  (JNIEnv *, jobject);

/*
 * Class:     com_example_helloworldformc_MainActivity
 * Method:    hello_world_from_c
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloworldformc_MainActivity_hello_1world_1from_1c
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
