/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_helloworldfromc2_MainActivity */

#ifndef _Included_com_example_helloworldfromc2_MainActivity
#define _Included_com_example_helloworldfromc2_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_helloworldfromc2_MainActivity
 * Method:    h_e_1_llo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_helloworldfromc2_MainActivity_h_1e_11_1llo
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
