/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_aliwangwang_MainActivity */

#ifndef _Included_com_example_aliwangwang_MainActivity
#define _Included_com_example_aliwangwang_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_aliwangwang_MainActivity
 * Method:    login
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_example_aliwangwang_MainActivity_login
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
