/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_ndkcallback_DataProvider */

#ifndef _Included_com_example_ndkcallback_DataProvider
#define _Included_com_example_ndkcallback_DataProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_ndkcallback_DataProvider
 * Method:    callMethod1
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkcallback_DataProvider_callMethod1
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkcallback_DataProvider
 * Method:    callMethod2
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkcallback_DataProvider_callMethod2
  (JNIEnv *, jobject);

/*
 * Class:     com_example_ndkcallback_DataProvider
 * Method:    callMethod3
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_ndkcallback_DataProvider_callMethod3
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
