/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_error_DemoActivity */

#ifndef _Included_com_example_error_DemoActivity
#define _Included_com_example_error_DemoActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_error_DemoActivity
 * Method:    helloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_error_DemoActivity_helloWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
