/*! ver:1392089005 Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var k=void 0,l=!0,p=null,q=!1,z=window.BAIDU_DUP_require,E=window.BAIDU_DUP_define;
E&&E("union/common/oo1392089005",[],function(){function d(a){var b=d.create(d);return a.call(b,b,b.Ea)}function h(a,b){if(a.constructor===Array)for(var e=0,c=a.length;e<c;e++){if(b.call(a,a[e],e,a)===q)return q}else{var e=!{toString:1}.propertyIsEnumerable("toString"),d="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(c in a)if(a.hasOwnProperty(c)&&b.call(a,a[c],c,a)===q)return q;if(e){e=0;for(c=d.length;e<c;e++){var f=d[e];if(a.hasOwnProperty(f)&&
b.call(a,f,e,a)===q)return q}}}return l}function c(a,b,c){h(b,function(b,d){if(!a.hasOwnProperty(d)||c)a[d]=b})}function g(a){function b(){}if(Object.create)return Object.create(a);b.prototype=a;return new b}d.Ea={};d.create=g;d.qb=h;d.Da=function(a){var b,e=a.hasOwnProperty("constructor")?a.constructor:function(){};e.prototype=a;e.prototype.constructor=e;b=b||{};b.wa&&c(e,b.wa);return e};d.extend=function(a,b,e){var d;d=b.hasOwnProperty("constructor")?b.constructor:function(){a.constructor.apply(this,
arguments)};d.prototype=g(a.prototype);c(d.prototype,b,l);d.prototype.constructor=d;d.prototype.Sb=a.prototype;c(d,a);e=e||{};e.wa&&c(d,e.wa,l);return d};d.jc=function(a){var b=this.Ea;h(a.split("."),function(a){b.hasOwnProperty(a)||(b[a]={});b=b[a]});return b};d.h=function(a,b){var c;return function(){c=c||[];for(var d=0,j=arguments.length;d<j;d++)c.push(arguments[d]);return a.apply(b||{},c)}};return d});
E&&E("union/common/cookie1392089005",[],function(){return{T:function(d,h){var c,g=RegExp("(^| )"+d+"=([^;]*)(;|$)").exec((h||window).document.cookie);g&&(c=g[2]);return c},va:function(d,h,c){var c=c||{},g=c.F;"number"==typeof c.F&&(g=new Date,g.setTime(g.getTime()+c.F));document.cookie=""+d+"="+h+(c.path?"; path="+c.path:"")+(g?"; expires="+g.toGMTString():"")+(c.domain?"; domain="+c.domain:"")+(c.oc?"; secure":"")},remove:function(d){var h=new Date;h.setTime(h.getTime()-86400);this.pc(d,"",{path:"/",F:h})}}});
E&&E("union/common/bom1392089005",[],function(){var d={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(d.a=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(d.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(d.Yb=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(d.nc=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(d.Ub=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.hc)&&
(d.ic=+RegExp.$1)}catch(h){}d.Ta=/webkit/i.test(navigator.userAgent);d.Db=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);d.Sa="CSS1Compat"==document.compatMode;return{f:d,t:function(){var c=l;if(this.f.a&&(7>this.f.a||"BackCompat"===document.compatMode))c=q;return c},cc:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.scrollWidth:c.document.documentElement.scrollWidth}catch(d){return 0}},bc:function(c){try{return c=c||window,"BackCompat"===
c.document.compatMode?c.document.body.scrollHeight:c.document.documentElement.scrollHeight}catch(d){return 0}},ma:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.clientWidth:c.document.documentElement.clientWidth}catch(d){return 0}},R:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.clientHeight:c.document.documentElement.clientHeight}catch(d){return 0}},U:function(c){c=(c||window).document;return window.pageYOffset||c.documentElement.scrollTop||
c.body.scrollTop},Oa:function(c){c=(c||window).document;return window.pageXOffset||c.documentElement.scrollLeft||c.body.scrollLeft},Ua:function(c){var d=q;try{c&&"object"===typeof c&&c.document&&"setInterval"in c&&(d=l)}catch(a){d=q}return d},H:function(c){c=c||window;return c!=window.top&&c!=c.parent||!this.Ua(c)},W:function(c,d){for(var d=2===arguments.length?d:c.parent,a=0;10>a++&&this.H(c,d);){var b;try{b=!!c.parent.location.toString()}catch(e){b=q}if(!b)return l;c=c.parent}return 10<=a?l:q},
Ib:function(c,d){var a=new Image,b="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),d=d||window;d[b]=a;a.onload=a.onerror=a.onabort=function(){a.onload=a.onerror=a.onabort=p;a=d[b]=p};a.src=c},na:function(c){if(!c)return document;"string"===typeof c&&(c=document.getElementById(c));return 9===c.nodeType?c:c.ownerDocument||c.document},oa:function(c){"string"===typeof c&&(c=document.getElementById(c));c=this.na(c);return c.parentWindow||c.defaultView||p},fc:function(c){c=c||window;return this.H(c)&&
!this.W(c,c.top)&&this.Ua(c.top)?c.top:c}}});
E&&E("union/common/dom1392089005",["union/common/oo1392089005","union/common/bom1392089005"],function(d,h){return d(function(c){var d=h.f;return{Zb:function(a,b){return"string"===typeof a||a instanceof String?(b||window).document.getElementById(a):a},Ra:function(a,b){var e=l;if("string"===typeof b)return a.id===b;if(b.constructor===Object)return c.qb(b,function(b,c){var d=(a.getAttribute?a.getAttribute(c):a[c])||a[c];if("tagName"===c){if(d.toUpperCase()!=b.toUpperCase())return e=q}else if(d!=b)return e=q}),e;if(b.constructor===
Array){var d=b.concat([]);d.reverse();for(var j=a;j&&d.length;j=j.parentNode)this.Ra(j,d[0])&&d.shift();return!d.length?l:q}},fb:function(a,b){if(a&&b(a)!==q){var e=a.childNodes;if(e)for(var c=0,d=e.length;c<d;c++)if(this.fb(e[c],b)===q)return q}},ab:function(a,b){var e=this;a.constructor===Object&&(a=this.e(a));if("string"===typeof b){for(var c=document.getElementById(b),d=c;d;){if(d===a)return c;d=d.parentNode}return p}if(b.constructor===Object){var f=p;e.fb(a,function(a){if(e.Ra(a,b))return f=
a,q});return f}},e:function(a){if(a){if(a.nodeName)return a;1<arguments.length&&(a=Array.prototype.slice.call(arguments,0));if("string"===typeof a)return document.getElementById(a);if(a.constructor===Object)return this.ab(document.documentElement,a);if(a.constructor===Array){for(var b=a.concat([]),e=document.documentElement;b.length&&e;)e=this.ab(e,b.shift());return e}}},lc:function(a,b,e){var e=e||this.rc||window,i=e.document;this.Ka=0;this.A=this.A||[];this.A.push({la:a,Ja:b||0,ia:q});var j=c.h(function(){var a=
q;this.Ka++;var b=q;try{e.frameElement&&(b=l)}catch(c){b=l}if(d.a&&9>d.a&&!b)try{i.documentElement.doScroll("left"),a=l}catch(j){}else if("complete"===i.readyState||this.pb)a=l;else if(3E5<this.Ka){this.u&&(e.clearInterval(this.u),this.u=p);return}if(a)try{if(this.A&&this.A.length)for(var a=0,h=this.A.length;a<h;a++){var n=this.A[a];n&&n.la&&!n.ia&&(n.Ja?(n.ia=l,e.setTimeout(n.la,n.Ja)):(n.ia=l,n.la()))}}catch(s){throw s;}finally{this.u&&(e.clearInterval(this.u),this.u=p)}},this),a=c.h(function(){this.pb=
l;j()},this);this.u||(this.u=e.setInterval(j,50),i.addEventListener?(i.addEventListener("DOMContentLoaded",a,q),e.addEventListener("load",a,q)):i.attachEvent&&e.attachEvent("onload",a,q))},t:function(){var a=l;if(d.a&&(7>d.a||"BackCompat"===document.compatMode))a=q;return a},bind:function(a,b,e){"string"===typeof a&&(a=this.e(a));b=b.replace(/^on/i,"").toLowerCase();a.addEventListener?a.addEventListener(b,e,q):a.attachEvent&&a.attachEvent("on"+b,e);return a},qc:function(a,b,e){a=this.e(a);b=b.replace(/^on/i,
"").toLowerCase();a.removeEventListener?a.removeEventListener(b,e,q):a.detachEvent&&a.detachEvent("on"+b,e);return a},g:function(a,b){var e;"string"===typeof a&&(a=this.e(a));var c=h.na(a),d="",d=-1<b.indexOf("-")?b.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):b.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});c&&c.defaultView&&c.defaultView.getComputedStyle?((c=c.defaultView.getComputedStyle(a,p))&&(e=c.getPropertyValue(b)),"boolean"!==typeof e&&!e&&
(e=c.getPropertyValue(d))):a.currentStyle&&((c=a.currentStyle)&&(e=c[b]),"boolean"!==typeof e&&!e&&(e=c[d]));return e},Bb:function(a,b){b=b||window;"string"===typeof a&&(a=this.e(a));if(a){for(var e=this.S(a),c,d=0;b!=b.parent&&10>d;)d++,c=this.S(b.frameElement),e.left+=c.left,e.top+=c.top,b=b.parent;return e}},S:function(a){"string"===typeof a&&(a=this.e(a));var b=h.na(a),e=h.f;0<e.Db&&b.getBoxObjectFor&&this.g(a,"position");var c={left:0,top:0},d;if(a==(e.a&&!e.Sa?b.body:b.documentElement)||!a)return c;
if(a.getBoundingClientRect)a=a.getBoundingClientRect(),c.left=Math.floor(a.left)+Math.max(b.documentElement.scrollLeft,b.body.scrollLeft),c.top=Math.floor(a.top)+Math.max(b.documentElement.scrollTop,b.body.scrollTop),c.left-=b.documentElement.clientLeft,c.top-=b.documentElement.clientTop,a=b.body,b=parseInt(this.g(a,"borderLeftWidth"),10),a=parseInt(this.g(a,"borderTopWidth"),10),e.a&&!e.Sa&&(c.left-=isNaN(b)?2:b,c.top-=isNaN(a)?2:a);else{d=a;do{c.left+=d.offsetLeft;c.top+=d.offsetTop;if(0<e.Ta&&
"fixed"==this.g(d,"position")){c.left+=b.body.scrollLeft;c.top+=b.body.scrollTop;break}d=d.offsetParent}while(d&&d!=a);if(0<e.opera||0<e.Ta&&"absolute"==this.g(a,"position"))c.top-=b.body.offsetTop;for(d=a.offsetParent;d&&d!=b.body;){c.left-=d.scrollLeft;if(!e.opera||"TR"!=d.tagName)c.top-=d.scrollTop;d=d.offsetParent}}return c},Ab:function(a,b){var a=this.e(a),e=a.offsetWidth;if(b||q)var c=this.g(a,"marginLeft").toString().toLowerCase().replace("px","").replace("auto","0"),d=this.g(a,"marginRight").toString().toLowerCase().replace("px",
"").replace("auto","0"),e=e+(parseInt(c||0,10)+parseInt(d||0,10));return e},zb:function(a,b){var a=this.e(a),e=a.offsetHeight;if(b||q)var c=this.g(a,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),d=this.g(a,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),e=e+(parseInt(c||0,10)+parseInt(d||0,10));return e},ec:function(a){var a=this.e(a),b=this.oa(a),e=0;if(this.H(window)&&!h.W(window)){for(;b.parent!=window.top&&10>e;)e++,b=b.parent;10>e&&(a=
b.frameElement||a)}return a},Ma:function(a){var b=this.e(a),a=this.oa(b),e=100,c;try{for(;b&&b.tagName;){c=100;if(this.f.a){if(5<this.f.a)try{c=b.Xb.alpha.opacity||100}catch(d){}e=e>c?c:e}else{try{c=100*(a.getComputedStyle(b,p).opacity||1)}catch(f){}e*=c/100}b=b.parentNode}}catch(g){}return e||100},ac:function(a){for(var b=this.e(a),a=this.oa(b),b=this.Ma(b),e=100,c=0;this.H(a);){c++;if(h.W(a,a.parent))break;else e=100,a.frameElement&&(e=this.Ma(a.frameElement)),b*=e/100;a=a.parent}return b}}})});
E&&E("union/common/logic1392089005",[],function(){return{Wb:function(d){(d=d||"")&&(d=d.replace(/%u[\d|\w]{4}/g,function(d){return encodeURIComponent(unescape(d))}));return d},bb:function(d,h){return d.replace(/{(.*?)}/g,function(c,d){return h[d]||""})},Eb:function(d){return(new Function("return "+d))()},Pa:function(d,h){if(d&&h){var c=d.match(RegExp("(^|&|\\?|#)"+h+"=([^&]*)(&|$)",""));if(c)return c[2]}return p},kc:function(d,h){var d=d||"",h=h||"?",c=arguments.callee;c.hasOwnProperty[h]||(c[h]={});c=c[h];
if(c.hasOwnProperty(d))return c[d];var g={},a=d.indexOf(h),b=d.substring(a+1).split("&");if(-1!==a)for(var a=0,e=b.length;a<e;a++){var i=b[a].split("="),j=decodeURIComponent(i[0]),i=decodeURIComponent(i[1]);g.hasOwnProperty(j)?(g[j].constructor!==Array&&(g[j]=[g[j]]),g[j].push(i)):g[j]=i}return c[d]=g}}});
E&&E("union/preview1392089005",["union/common/bom1392089005","union/common/logic1392089005","union/common/cookie1392089005"],function(d,h,c){function g(a){a=decodeURIComponent(a).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return h.Eb(a)}function a(a,e){var i;i=e?e.substring(e.indexOf("?")):d.W(window)?window.location.search.slice(1):window.top.location.search.slice(1);var j=document.referrer,f=0<=a.indexOf("inlay")||"ui"===a?"bd_cpro_prev":"bd_cpro_fprev",m="",v;try{v=document.cookie}catch(w){}-1!==
i.indexOf(f)&&(m=h.Pa(i,f));!m&&v&&-1!==v.indexOf(f)&&(m=c.T(f));!m&&-1!==j.indexOf(f)&&(m=h.Pa(j,f));return m}return{Na:function(b,e){var c=window.location.href,j=parseInt(b.rsi0,10),f=parseInt(b.rsi1,10),m=parseInt(b.at,10),v=q,w=a(e,c);if(w)if(w=g(w),m===k&&(m=1),1!==parseInt(w.type,10)&&2===(m&2))v=parseInt(w.imgWidth,10)===parseInt(j,10)&&parseInt(w.imgHeight,10)===parseInt(f,10);else if(1===parseInt(w.type,10)&&(1===(m&1)||64===(m&64)||32===(m&32)))v=l;return v?(j=0<=e.indexOf("inlay")||"ui"===
e?"bd_cpro_prev":"bd_cpro_fprev",c=a(e,c),f=b.tn,m=g(c),v=p,0<=e.indexOf("inlay")?v={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(m.type,10)?f+".html":2===parseInt(m.type,10)?"image.html":4===parseInt(m.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+j+"=#"+c+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===e&&(m=parseInt(m.type,10),m="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===m?"float_image.html":4===m?"float_flash.html":"blank_tips.html")+
"?",c="tn="+f+("&"+j+"="+c).replace(/\./g,"%252e")+"&ut="+ +new Date,v={serviceUrl:m,paramString:c}),v):p}}});
E&&E("union/business/businessLogic1392089005",["union/preview1392089005"],function(d){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},c={inlay:0,"float":0,patch:0,linkunit:0,popup:0},g={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{Wa:function(a){var b=a._html||{},c="",i="http://cb.baidu.com/ecom?",
j=a.id.split("_")[0],f=parseInt(b.conW||0,10)||parseInt(a._w,10)||parseInt(a.sw,10)||parseInt(b.rsi0,10),g=parseInt(b.conH||0,10)||parseInt(a._h,10)||parseInt(a.sh,10)||parseInt(b.rsi1,10),h=a.displayType,w=b.tn||"",G=w.toLowerCase(),n=b.ch||0,a=a.qn||"",s=b.n||"",t=b.dai||0;b.dtm="BAIDU_DUP2_SETJSONADSLOT";b.dc="2";b.di=j;var c=[],u;for(u in b)u&&b.hasOwnProperty(u)&&c.push(""+u+"="+encodeURIComponent(b[u].toString()));c=c.join("&");if((u=d.Na(b,h))&&u.serviceUrl!==k&&u.paramString!==k)i=u.serviceUrl,
c=u.paramString;return{slotId:j,slotWidth:f,slotHeight:g,displayType:h,styleType:G,unionAccount:s,adIndex:t,channel:n,pvId:a,stuffType:"unknown",serviceUrl:i,paramString:c,delayIn:b.delayIn,delayOut:b.delayOut,sessionSync:b.sessionSync!==q&&"false"!==b.sessionSync,closeFor:b.closeFor,xuantingType:b.xuanting,tn:w}},ra:function(a){var b={};b.ob=(a.ob||"pc").toLowerCase();b.k=(a.k||"inlay-fixed").toLowerCase();b.i=(a.i||"template_inlay_all_normal").toLowerCase();b.B=(a.B||"text").toLowerCase();if(-1<
b.i.indexOf("tlink")||-1<b.i.indexOf("linkunit"))b.k="linkunit-fixed";0<=b.i.indexOf("float_xuanfuwin")&&(b.k="popup-float");a=b.k.split("-");b.Q=a[0]||"inlay";b.Vb=a[1]||"fixed";return b},ca:function(a){a=this.ra(a);a=a.Q;return c[a]<h[a]},$b:function(a){a=this.ra(a);return c[a.Q]},ua:function(a){a=this.ra(a);c[a.Q]+=1;return l},Qa:function(a,b){var c=document.getElementById("cpro_"+a);c||(c=document.getElementById(b));return c},ub:function(a){return g[a]},mb:function(a){var b={"test.com":l,"people.com.cn":l,
"chinanews.com":l,"cri.cn":l,"chinadaily.com":l,"cnki.com.cn":l,"cnki.net":l,"ku6.com":l,"tgbus.com":l,"5068.com":l,"yzz.cn":l,"aipai.com":l,"stockstar.com":l},a=a||window,c="",d=a.document.domain.split("."),g=d.length;g&&2<g?c="cn"===d[g-1]&&"com"===d[g-2]?d[g-3]+"."+d[g-2]+"."+d[g-1]:d[g-2]+"."+d[g-1]:g&&(c=a.document.domain);return c&&b[c]?q:l}}});E&&E("union/floatad","union/common/oo1392089005,union/common/cookie1392089005,union/common/dom1392089005,union/common/bom1392089005,union/common/logic1392089005,union/business/businessLogic1392089005,union/preview1392089005".split(","),function(d,h,c,g,a,b,e){function i(a,j,c){if(!a||!a._html)return p;var i=b.ub(j),f=a._html,d="",g="http://cb.baidu.com/ecom?",h=a.id.split("_")[0],D=parseInt(f.conW||0,10)||parseInt(f.rsi0,10)||parseInt(a._w,10)||parseInt(a.sw,10),a=parseInt(f.conH||0,10)||parseInt(f.rsi1,10)||parseInt(a._h,10)||parseInt(a.sh,10),d=f.tn||"",H=d.toLowerCase(),
y=f.n||"",A=parseInt(f.ch||0,10),C=parseInt(f.dai||0,10);f.stid=0;var r=0<=d.indexOf("float")&&120===D&&270===a,x=q,B=parseInt(f.lunum,10);b.mb(window)&&r&&(0<B&&(f.lunum=6,x=l),f.stid=2);f.dtm="BAIDU_DUP2_SETJSONADSLOT";f.dc="2";f.di=h;f.distp=j;0<=d.indexOf("float")&&(f.tn="template_float_all_normal");var d=[],o;for(o in f)o&&f.hasOwnProperty(o)&&d.push(""+o+"="+encodeURIComponent(f[o].toString()));d=d.join("&");if((o=e.Na(f,i))&&o.serviceUrl!==k&&o.paramString!==k)g=o.serviceUrl,d=o.paramString;
return{m:h,$a:D,Za:a,k:i,ka:parseInt(f.rsi6,10),ja:parseInt(f.rsi7,10),ga:parseInt(f.ccw,10),da:parseInt(f.ct,10),G:parseInt(f.pt,10),z:c,j:parseInt(f.fa,10),sb:parseInt(f.flw,10),Mb:f.tn,Y:f.qn,i:H,v:g,l:d,b:"cproIframe"+(j||parseInt(100+100*Math.random(),10)),pa:x,K:y,D:A,N:C,B:"unknown"}}function j(a){var j=a.slotId,b=a.adIndex||0;z(["viewWatch"],function(f){f.register({id:j,wrapperId:a.b,logType:"block",extra:"did="+b+"&ch="+a.D+"&jk="+a.Y+"&tn="+a.Mb+"&n="+a.K+"&js=f&exp=60002"})},l)}var f;d(function(j){f=
j.Da({rb:{1:{Ca:1,Ba:150},2:{Ca:0,Ba:40},3:{Ca:0,Ba:0}},constructor:function(a){this.b=a.b;this.v=a.v;this.l=a.l;this.ha=this.b+"holder";this.j=a.j;this.z=a.z;this.G=a.G;this.La=a.sb;this.p=a.$a;this.o=a.Za;this.C=a.$a;this.s=a.Za;this.pa=a.pa;this.Y=a.Y;this.ka=a.ka;this.ja=a.ja;this.ga=a.ga;this.pa?(this.o+=80,this.s+=80):this.o+=20;this.Ha=1===this.j?0:5;this.p+=10;this.o+=10;this.C+=10;this.s+=10;this.cb=this.rb;this.da=a.da;this.m=a.m;this.t=g.t();c.bind(window,"resize",j.h(this.$,this));c.bind(window,
"scroll",j.h(this.$,this))},ta:function(){var b=document.createElement("div");b.style.cssText=["maring:0;padding:0;display:block;visibility:visible;border:none;background:none;float:none;overflow:hidden;position:absolute;","z-index:"+(1===this.j?2147483646:2147483647)+";","width:"+this.p+"px;","height:"+(this.o+this.Ha)+"px"].join("");b.id=this.ha;var f="",c=document.createElement("div");c.id=this.b+"CloseBtnWrap";var e=document.createElement("div");e.id=this.b+"CloseBtn";1===this.j?(c.style.cssText=
["position:absolute;top:275px;left:0;cursor:pointer;","width:"+this.p+"px;","height:28px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;"].join(""),e.style.cssText=["position:absolute;","width:"+this.p+"px;","height:20px;top:280px;left:0;cursor:pointer;background-color:#999999;color:#fff;font-size:12px;font-family: \u5fae\u8f6f\u96c5\u9ed1;text-align:center;line-height:20px;"].join(""),e.innerHTML="\u5173\u95ed"):(c.style.cssText=["position:absolute;top:0px;","left:"+(this.p-
61)+"px;","cursor:pointer;width:61px;height:20px;z-index:100;opacity:0;filter:alpha(opacity=0);background-color:#999999;margin:0;paddong:0;"].join(""),e.style.cssText=["position:absolute;width:61px;height:20px;top:0;","left:"+(this.p-61)+"px;","margin:0;padding:0;margin-bottom:5px;cursor:pointer;overflow:hidden;"].join(""),e.innerHTML='<div style="width:40px;height:20px;background-color:#999999;color:#fff;float:left;margin-right:1px;font-size:12px;font-family:\u5fae\u8f6f\u96c5\u9ed1;text-align: center;line-height:20px;">\u5173\u95ed</div><a style="maring:0;padding:0;display:inline-block;border:none;overflow:hidden;height:20px;line-height:20px;cursor:pointer;width:20px;background:url(\'http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png\') no-repeat 0 0;margin-bottom:3px;float:left" ></a>',
f="position:absolute;left:0;top:25px;");b.appendChild(c);b.appendChild(e);e=document.createElement("div");e.style.cssText=["width:"+this.C+"px;","height:"+this.s+"px;","overflow:hidden;"+f].join("");this.l+="&adclass=1&conW="+this.C+"&conH="+this.s;e.innerHTML=a.bb('<div style="display:none">-</div><iframe id="{iframeId}" src="{cproServiceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true"></iframe></div>',
{iframeId:this.b,cproServiceUrl:this.v,paramString:this.l,iframeWidth:this.C,iframeHeight:this.s});b.appendChild(e);this.Z(b);for(var f=document.body.children,e=f.length,i=10>f.length?f.length:10,d=document.body.lastChild,g=0;g<i;g++){var h=f[e-g-1].getAttribute("data-baidu-dan-id");if(h||""===h){d=f[e-g-1];break}}d.parentNode.insertBefore(b,d);c.onclick=j.h(this.jb,this);c.onmouseover=j.h(this.lb,this);c.onmouseout=j.h(this.kb,this)},wb:function(){var a=2;return a=1===this.La?this.t?1===this.G?4:
3:1===this.G?2:1:1===this.G?6:5},vb:function(){var a=this.ja;return a=0>a||9999<a?0:Math.floor(a)},xb:function(){var a=this.ka;return a=0>a||9999<a?this.cb[this.j].Ba:Math.floor(a)},tb:function(){var a=this.ga;4095<a&&(a=4095);return a=Math.floor(a)},$:function(){this.J&&clearTimeout(this.J);this.J=setTimeout(j.h(this.Kb,this),50)},Kb:function(){var a=document.getElementById(this.ha);a&&this.Z(a)},Z:function(a){a.style.position=this.t?(1===this.j||2===this.j)&&2===this.La?"absolute":"fixed":"absolute";
var j=g.U(window),b=g.Oa(window),f=g.ma(window),e=g.R(window),i=this.p,m=this.o+this.Ha,d=this.cb[this.j].Ca,h=c.g(document.body,"position").toString(),y=c.g(document.body,"width").toString().replace("px",""),A=this.wb(),C="right",r,x,B=this.vb(),o=this.xb();r=this.tb();var F=c.Bb(document.body).left;r=Math.floor((f-r)/2)-i-10;r=0<=r&&0==A%2?r:7;switch(A){case 1:case 2:"relative"===h&&"auto"!=y&&f>y?(i=f-r-i-F,b=b+r-F):(i=b+f-r-i,b+=r);C="left";x=Math.max(1===d?e>=m+o?j+o:j+e-m:e>=m+o?j+e-o-m:j,B);
break;case 3:case 4:b=i=r;1===d?x=Math.max(e>=m+o?o:e-m,B-j):(x=Math.min(j+e-B-m,o),x=Math.min(x,e-m));break;case 5:case 6:"relative"===h&&"auto"!=y&&f>y?(i=f-(f-y)/2-r-i,b=b+r-(f-y)/2):(i=b+f-r-i,b+=r);C="left";x=Math.max(1===d?o:e>=m+o?e-o-m:0,B);break;default:b=i=10}if(1===A%4||2===A%4)d=1;j=d?"top":"bottom";1===(this.z&1)?(a=a.style,a.left=b+"px",a[j]=x+"px",a.visibility="visible"):2===(this.z&2)&&(a=a.style,a[C]=i+"px",a[j]=x+"px",a.visibility="visible")},jb:function(){var j=document.getElementById(this.ha);
if(2===this.da){var b="bd_close_"+this.m,f=h.T(b,window),f=f?f|this.z:this.z;h.va(b,f,{path:"/"})}document.body.removeChild(j);j={jk:this.Y||"",dt:(new Date).getTime(),rnd:Math.floor(2147483648*Math.random())};try{g.Ib(a.bb("http://eclick.baidu.com/fcb.jpg?jk={jk}&dt={dt}&rnd={rnd}",j),window)}catch(e){}},lb:function(){var a=document.getElementById(this.b+"CloseBtn");a&&(1===this.j?a.style.backgroundColor="#0066cc":(a.getElementsByTagName("div")[0].style.backgroundColor="#0066cc",a.getElementsByTagName("a")[0].style.backgroundImage=
"url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.0/xuanfu_mouseover_close.png)"))},kb:function(){var a=document.getElementById(this.b+"CloseBtn");a&&(1===this.j?a.style.backgroundColor="#999999":(a.getElementsByTagName("div")[0].style.backgroundColor="#999999",a.getElementsByTagName("a")[0].style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/2.0.1/xuanfu_close.png)"))}})});return{render:function(a){var e;if(g.H())e=q;else if(e=parseInt(a._html.ww||0,10),4095<e&&(e=
4095),e>=screen.width)e=q;else{var c=e=q;e=/iphone|ipod|android|blackberry|opera mini|opera mobi|skyfire|maemo|windows phone|palm|iemobile|symbian|symbianos|fennec/i.test(navigator.userAgent.toLowerCase());c=/ipad|android 3|sch-i800|playbook|tablet|kindle|gt-p1000|sgh-t849|shw-m180s|a510|a511|a100|dell streak|silk|SAMSUNG.*Tablet|Galaxy.*Tab|SC-01C|GT-P1000|GT-P1003|GT-P1010|GT-P3105|GT-P6210|GT-P6800|GT-P6810|GT-P7100|GT-P7300|GT-P7310|GT-P7500|GT-P7510|SCH-I800|SCH-I815|SCH-I905|SGH-I957|SGH-I987|SGH-T849|SGH-T859|SGH-T869|SPH-P100|GT-P3100|GT-P3108|GT-P3110|GT-P5100|GT-P5110|GT-P6200|GT-P7320|GT-P7511|GT-N8000|GT-P8510|SGH-I497|SPH-P500|SGH-T779|SCH-I705|SCH-I915|GT-N8013|GT-P3113|GT-P5113|GT-P8110|GT-N8010|GT-N8005|GT-N8020|GT-P1013|GT-P6201|GT-P7501|GT-N5100|GT-N5110|SHV-E140K|SHV-E140L|SHV-E140S|SHV-E150S|SHV-E230K|SHV-E230L|SHV-E230S|SHW-M180K|SHW-M180L|SHW-M180S|SHW-M180W|SHW-M300W|SHW-M305W|SHW-M380K|SHW-M380S|SHW-M380W|SHW-M430W|SHW-M480K|SHW-M480S|SHW-M480W|SHW-M485W|SHW-M486W|SHW-M500W|GT-I9228|SCH-P739|SCH-I925|GT-I9200|GT-I9205|GT-P5200|GT-P5210|SM-T311|SM-T310|SM-T210|SM-T211|SM-P900|IdeaTab|S2110|S6000|K3011|A3000|A1000|A2107|A2109|A1107/i.test(navigator.userAgent.toLowerCase());
e=1024>screen.width&&e&&!c?q:l}if(e){if(a&&a._html){var d=a._html;e=parseInt(d.fa,10);var c=parseInt(d.ls,10),n=a.id.split("_")[0],s=0;2===parseInt(d.ct,10)&&(s=parseInt(h.T("bd_close_"+n),10));d=[];1===e||2===e?(2===(c&2)&&2!==(s&2)&&d.push(i(a,"2002",2)),1===(c&1)&&1!==(s&1)&&d.push(i(a,"2001",1))):(c=3!==c?c:2,s!=c&&d.push(i(a,1===c?"2003":"2004",c)));a=d}else a=k;e=a.length;for(c=0;c<e;c++)if(s=a[c])d={k:s.k,i:s.i,B:s.B},b.ca(d)&&((new f(s)).ta(),b.ua(d),j(s))}}}});
})();
