/*! ver:1392089005 Copyright 2014 Baidu Inc. All Rights Reserved. */;(function(){var k=void 0,l=!0,p=null,q=!1,z=window.BAIDU_DUP_require,E=window.BAIDU_DUP_define;
E&&E("union/common/cookie1392089005",[],function(){return{T:function(d,h){var c,g=RegExp("(^| )"+d+"=([^;]*)(;|$)").exec((h||window).document.cookie);g&&(c=g[2]);return c},va:function(d,h,c){var c=c||{},g=c.F;"number"==typeof c.F&&(g=new Date,g.setTime(g.getTime()+c.F));document.cookie=""+d+"="+h+(c.path?"; path="+c.path:"")+(g?"; expires="+g.toGMTString():"")+(c.domain?"; domain="+c.domain:"")+(c.oc?"; secure":"")},remove:function(d){var h=new Date;h.setTime(h.getTime()-86400);this.pc(d,"",{path:"/",F:h})}}});
E&&E("union/common/bom1392089005",[],function(){var d={};/msie (\d+\.\d)/i.test(navigator.userAgent)&&(d.a=document.documentMode||+RegExp.$1);/opera\/(\d+\.\d)/i.test(navigator.userAgent)&&(d.opera=+RegExp.$1);/firefox\/(\d+\.\d)/i.test(navigator.userAgent)&&(d.Yb=+RegExp.$1);/(\d+\.\d)?(?:\.\d)?\s+safari\/?(\d+\.\d+)?/i.test(navigator.userAgent)&&!/chrome/i.test(navigator.userAgent)&&(d.nc=+(RegExp.$1||RegExp.$2));/chrome\/(\d+\.\d)/i.test(navigator.userAgent)&&(d.Ub=+RegExp.$1);try{/(\d+\.\d)/.test(window.external.hc)&&
(d.ic=+RegExp.$1)}catch(h){}d.Ta=/webkit/i.test(navigator.userAgent);d.Db=/gecko/i.test(navigator.userAgent)&&!/like gecko/i.test(navigator.userAgent);d.Sa="CSS1Compat"==document.compatMode;return{f:d,t:function(){var c=l;if(this.f.a&&(7>this.f.a||"BackCompat"===document.compatMode))c=q;return c},cc:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.scrollWidth:c.document.documentElement.scrollWidth}catch(d){return 0}},bc:function(c){try{return c=c||window,"BackCompat"===
c.document.compatMode?c.document.body.scrollHeight:c.document.documentElement.scrollHeight}catch(d){return 0}},ma:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.clientWidth:c.document.documentElement.clientWidth}catch(d){return 0}},R:function(c){try{return c=c||window,"BackCompat"===c.document.compatMode?c.document.body.clientHeight:c.document.documentElement.clientHeight}catch(d){return 0}},U:function(c){c=(c||window).document;return window.pageYOffset||c.documentElement.scrollTop||
c.body.scrollTop},Oa:function(c){c=(c||window).document;return window.pageXOffset||c.documentElement.scrollLeft||c.body.scrollLeft},Ua:function(c){var d=q;try{c&&"object"===typeof c&&c.document&&"setInterval"in c&&(d=l)}catch(a){d=q}return d},H:function(c){c=c||window;return c!=window.top&&c!=c.parent||!this.Ua(c)},W:function(c,d){for(var d=2===arguments.length?d:c.parent,a=0;10>a++&&this.H(c,d);){var b;try{b=!!c.parent.location.toString()}catch(e){b=q}if(!b)return l;c=c.parent}return 10<=a?l:q},
Ib:function(c,d){var a=new Image,b="cpro_log_"+Math.floor(2147483648*Math.random()).toString(36),d=d||window;d[b]=a;a.onload=a.onerror=a.onabort=function(){a.onload=a.onerror=a.onabort=p;a=d[b]=p};a.src=c},na:function(c){if(!c)return document;"string"===typeof c&&(c=document.getElementById(c));return 9===c.nodeType?c:c.ownerDocument||c.document},oa:function(c){"string"===typeof c&&(c=document.getElementById(c));c=this.na(c);return c.parentWindow||c.defaultView||p},fc:function(c){c=c||window;return this.H(c)&&
!this.W(c,c.top)&&this.Ua(c.top)?c.top:c}}});
E&&E("union/common/oo1392089005",[],function(){function d(a){var b=d.create(d);return a.call(b,b,b.Ea)}function h(a,b){if(a.constructor===Array)for(var e=0,c=a.length;e<c;e++){if(b.call(a,a[e],e,a)===q)return q}else{var e=!{toString:1}.propertyIsEnumerable("toString"),d="toString,toLocaleString,valueOf,constructor,propertyIsEnumerable,hasOwnProperty,isPrototypeOf".split(",");for(c in a)if(a.hasOwnProperty(c)&&b.call(a,a[c],c,a)===q)return q;if(e){e=0;for(c=d.length;e<c;e++){var f=d[e];if(a.hasOwnProperty(f)&&
b.call(a,f,e,a)===q)return q}}}return l}function c(a,b,c){h(b,function(b,d){if(!a.hasOwnProperty(d)||c)a[d]=b})}function g(a){function b(){}if(Object.create)return Object.create(a);b.prototype=a;return new b}d.Ea={};d.create=g;d.qb=h;d.Da=function(a){var b,e=a.hasOwnProperty("constructor")?a.constructor:function(){};e.prototype=a;e.prototype.constructor=e;b=b||{};b.wa&&c(e,b.wa);return e};d.extend=function(a,b,e){var d;d=b.hasOwnProperty("constructor")?b.constructor:function(){a.constructor.apply(this,
arguments)};d.prototype=g(a.prototype);c(d.prototype,b,l);d.prototype.constructor=d;d.prototype.Sb=a.prototype;c(d,a);e=e||{};e.wa&&c(d,e.wa,l);return d};d.jc=function(a){var b=this.Ea;h(a.split("."),function(a){b.hasOwnProperty(a)||(b[a]={});b=b[a]});return b};d.h=function(a,b){var c;return function(){c=c||[];for(var d=0,j=arguments.length;d<j;d++)c.push(arguments[d]);return a.apply(b||{},c)}};return d});
E&&E("union/common/dom1392089005",["union/common/oo1392089005","union/common/bom1392089005"],function(d,h){return d(function(c){var d=h.f;return{Zb:function(a,b){return"string"===typeof a||a instanceof String?(b||window).document.getElementById(a):a},Ra:function(a,b){var e=l;if("string"===typeof b)return a.id===b;if(b.constructor===Object)return c.qb(b,function(b,c){var d=(a.getAttribute?a.getAttribute(c):a[c])||a[c];if("tagName"===c){if(d.toUpperCase()!=b.toUpperCase())return e=q}else if(d!=b)return e=q}),e;if(b.constructor===
Array){var d=b.concat([]);d.reverse();for(var j=a;j&&d.length;j=j.parentNode)this.Ra(j,d[0])&&d.shift();return!d.length?l:q}},fb:function(a,b){if(a&&b(a)!==q){var e=a.childNodes;if(e)for(var c=0,d=e.length;c<d;c++)if(this.fb(e[c],b)===q)return q}},ab:function(a,b){var e=this;a.constructor===Object&&(a=this.e(a));if("string"===typeof b){for(var c=document.getElementById(b),d=c;d;){if(d===a)return c;d=d.parentNode}return p}if(b.constructor===Object){var f=p;e.fb(a,function(a){if(e.Ra(a,b))return f=
a,q});return f}},e:function(a){if(a){if(a.nodeName)return a;1<arguments.length&&(a=Array.prototype.slice.call(arguments,0));if("string"===typeof a)return document.getElementById(a);if(a.constructor===Object)return this.ab(document.documentElement,a);if(a.constructor===Array){for(var b=a.concat([]),e=document.documentElement;b.length&&e;)e=this.ab(e,b.shift());return e}}},lc:function(a,b,e){var e=e||this.rc||window,i=e.document;this.Ka=0;this.A=this.A||[];this.A.push({la:a,Ja:b||0,ia:q});var j=c.h(function(){var a=
q;this.Ka++;var b=q;try{e.frameElement&&(b=l)}catch(c){b=l}if(d.a&&9>d.a&&!b)try{i.documentElement.doScroll("left"),a=l}catch(j){}else if("complete"===i.readyState||this.pb)a=l;else if(3E5<this.Ka){this.u&&(e.clearInterval(this.u),this.u=p);return}if(a)try{if(this.A&&this.A.length)for(var a=0,h=this.A.length;a<h;a++){var n=this.A[a];n&&n.la&&!n.ia&&(n.Ja?(n.ia=l,e.setTimeout(n.la,n.Ja)):(n.ia=l,n.la()))}}catch(s){throw s;}finally{this.u&&(e.clearInterval(this.u),this.u=p)}},this),a=c.h(function(){this.pb=
l;j()},this);this.u||(this.u=e.setInterval(j,50),i.addEventListener?(i.addEventListener("DOMContentLoaded",a,q),e.addEventListener("load",a,q)):i.attachEvent&&e.attachEvent("onload",a,q))},t:function(){var a=l;if(d.a&&(7>d.a||"BackCompat"===document.compatMode))a=q;return a},bind:function(a,b,e){"string"===typeof a&&(a=this.e(a));b=b.replace(/^on/i,"").toLowerCase();a.addEventListener?a.addEventListener(b,e,q):a.attachEvent&&a.attachEvent("on"+b,e);return a},qc:function(a,b,e){a=this.e(a);b=b.replace(/^on/i,
"").toLowerCase();a.removeEventListener?a.removeEventListener(b,e,q):a.detachEvent&&a.detachEvent("on"+b,e);return a},g:function(a,b){var e;"string"===typeof a&&(a=this.e(a));var c=h.na(a),d="",d=-1<b.indexOf("-")?b.replace(/[-_][^-_]{1}/g,function(a){return a.charAt(1).toUpperCase()}):b.replace(/[A-Z]{1}/g,function(a){return"-"+a.charAt(0).toLowerCase()});c&&c.defaultView&&c.defaultView.getComputedStyle?((c=c.defaultView.getComputedStyle(a,p))&&(e=c.getPropertyValue(b)),"boolean"!==typeof e&&!e&&
(e=c.getPropertyValue(d))):a.currentStyle&&((c=a.currentStyle)&&(e=c[b]),"boolean"!==typeof e&&!e&&(e=c[d]));return e},Bb:function(a,b){b=b||window;"string"===typeof a&&(a=this.e(a));if(a){for(var e=this.S(a),c,d=0;b!=b.parent&&10>d;)d++,c=this.S(b.frameElement),e.left+=c.left,e.top+=c.top,b=b.parent;return e}},S:function(a){"string"===typeof a&&(a=this.e(a));var b=h.na(a),e=h.f;0<e.Db&&b.getBoxObjectFor&&this.g(a,"position");var c={left:0,top:0},d;if(a==(e.a&&!e.Sa?b.body:b.documentElement)||!a)return c;
if(a.getBoundingClientRect)a=a.getBoundingClientRect(),c.left=Math.floor(a.left)+Math.max(b.documentElement.scrollLeft,b.body.scrollLeft),c.top=Math.floor(a.top)+Math.max(b.documentElement.scrollTop,b.body.scrollTop),c.left-=b.documentElement.clientLeft,c.top-=b.documentElement.clientTop,a=b.body,b=parseInt(this.g(a,"borderLeftWidth"),10),a=parseInt(this.g(a,"borderTopWidth"),10),e.a&&!e.Sa&&(c.left-=isNaN(b)?2:b,c.top-=isNaN(a)?2:a);else{d=a;do{c.left+=d.offsetLeft;c.top+=d.offsetTop;if(0<e.Ta&&
"fixed"==this.g(d,"position")){c.left+=b.body.scrollLeft;c.top+=b.body.scrollTop;break}d=d.offsetParent}while(d&&d!=a);if(0<e.opera||0<e.Ta&&"absolute"==this.g(a,"position"))c.top-=b.body.offsetTop;for(d=a.offsetParent;d&&d!=b.body;){c.left-=d.scrollLeft;if(!e.opera||"TR"!=d.tagName)c.top-=d.scrollTop;d=d.offsetParent}}return c},Ab:function(a,b){var a=this.e(a),e=a.offsetWidth;if(b||q)var c=this.g(a,"marginLeft").toString().toLowerCase().replace("px","").replace("auto","0"),d=this.g(a,"marginRight").toString().toLowerCase().replace("px",
"").replace("auto","0"),e=e+(parseInt(c||0,10)+parseInt(d||0,10));return e},zb:function(a,b){var a=this.e(a),e=a.offsetHeight;if(b||q)var c=this.g(a,"marginTop").toString().toLowerCase().replace("px","").replace("auto","0"),d=this.g(a,"marginBottom").toString().toLowerCase().replace("px","").replace("auto","0"),e=e+(parseInt(c||0,10)+parseInt(d||0,10));return e},ec:function(a){var a=this.e(a),b=this.oa(a),e=0;if(this.H(window)&&!h.W(window)){for(;b.parent!=window.top&&10>e;)e++,b=b.parent;10>e&&(a=
b.frameElement||a)}return a},Ma:function(a){var b=this.e(a),a=this.oa(b),e=100,c;try{for(;b&&b.tagName;){c=100;if(this.f.a){if(5<this.f.a)try{c=b.Xb.alpha.opacity||100}catch(d){}e=e>c?c:e}else{try{c=100*(a.getComputedStyle(b,p).opacity||1)}catch(f){}e*=c/100}b=b.parentNode}}catch(g){}return e||100},ac:function(a){for(var b=this.e(a),a=this.oa(b),b=this.Ma(b),e=100,c=0;this.H(a);){c++;if(h.W(a,a.parent))break;else e=100,a.frameElement&&(e=this.Ma(a.frameElement)),b*=e/100;a=a.parent}return b}}})});
E&&E("union/common/logic1392089005",[],function(){return{Wb:function(d){(d=d||"")&&(d=d.replace(/%u[\d|\w]{4}/g,function(d){return encodeURIComponent(unescape(d))}));return d},bb:function(d,h){return d.replace(/{(.*?)}/g,function(c,d){return h[d]||""})},Eb:function(d){return(new Function("return "+d))()},Pa:function(d,h){if(d&&h){var c=d.match(RegExp("(^|&|\\?|#)"+h+"=([^&]*)(&|$)",""));if(c)return c[2]}return p},kc:function(d,h){var d=d||"",h=h||"?",c=arguments.callee;c.hasOwnProperty[h]||(c[h]={});c=c[h];
if(c.hasOwnProperty(d))return c[d];var g={},a=d.indexOf(h),b=d.substring(a+1).split("&");if(-1!==a)for(var a=0,e=b.length;a<e;a++){var i=b[a].split("="),j=decodeURIComponent(i[0]),i=decodeURIComponent(i[1]);g.hasOwnProperty(j)?(g[j].constructor!==Array&&(g[j]=[g[j]]),g[j].push(i)):g[j]=i}return c[d]=g}}});
E&&E("union/preview1392089005",["union/common/bom1392089005","union/common/logic1392089005","union/common/cookie1392089005"],function(d,h,c){function g(a){a=decodeURIComponent(a).replace(/\\x1e/g,"&").replace(/\\x1d/g,"=").replace(/\\x1c/g,"?").replace(/\\x5c/g,"\\");return h.Eb(a)}function a(a,e){var i;i=e?e.substring(e.indexOf("?")):d.W(window)?window.location.search.slice(1):window.top.location.search.slice(1);var j=document.referrer,f=0<=a.indexOf("inlay")||"ui"===a?"bd_cpro_prev":"bd_cpro_fprev",m="",v;try{v=document.cookie}catch(w){}-1!==
i.indexOf(f)&&(m=h.Pa(i,f));!m&&v&&-1!==v.indexOf(f)&&(m=c.T(f));!m&&-1!==j.indexOf(f)&&(m=h.Pa(j,f));return m}return{Na:function(b,e){var c=window.location.href,j=parseInt(b.rsi0,10),f=parseInt(b.rsi1,10),m=parseInt(b.at,10),v=q,w=a(e,c);if(w)if(w=g(w),m===k&&(m=1),1!==parseInt(w.type,10)&&2===(m&2))v=parseInt(w.imgWidth,10)===parseInt(j,10)&&parseInt(w.imgHeight,10)===parseInt(f,10);else if(1===parseInt(w.type,10)&&(1===(m&1)||64===(m&64)||32===(m&32)))v=l;return v?(j=0<=e.indexOf("inlay")||"ui"===
e?"bd_cpro_prev":"bd_cpro_fprev",c=a(e,c),f=b.tn,m=g(c),v=p,0<=e.indexOf("inlay")?v={serviceUrl:"http://cpro.baidu.com/cpro/ui/preview/templates/"+(1===parseInt(m.type,10)?f+".html":2===parseInt(m.type,10)?"image.html":4===parseInt(m.type,10)?"flash.html":"blank_tips.html")+"?",paramString:(""+j+"=#"+c+"&ut="+ +new Date).replace(/\.(?!swf)/g,"%252e")}:"float"===e&&(m=parseInt(m.type,10),m="http://cpro.baidu.com/cpro/ui/preview/templates/"+(2===m?"float_image.html":4===m?"float_flash.html":"blank_tips.html")+
"?",c="tn="+f+("&"+j+"="+c).replace(/\./g,"%252e")+"&ut="+ +new Date,v={serviceUrl:m,paramString:c}),v):p}}});
E&&E("union/business/businessLogic1392089005",["union/preview1392089005"],function(d){var h={inlay:8,"float":2,patch:2,linkunit:20,popup:1},c={inlay:0,"float":0,patch:0,linkunit:0,popup:0},g={1001:"inlay-fixed",1002:"inlay-float",2001:"float-left-middle",2002:"float-right-middle",2003:"float-left-bottom",2004:"float-right-bottom",2005:"float-top",2006:"float-bottom",2007:"float-linkunit-left",3001:"patch-webpage",3002:"patch-flash",4001:"captcha-webpage"};return{Wa:function(a){var b=a._html||{},c="",i="http://cb.baidu.com/ecom?",
j=a.id.split("_")[0],f=parseInt(b.conW||0,10)||parseInt(a._w,10)||parseInt(a.sw,10)||parseInt(b.rsi0,10),g=parseInt(b.conH||0,10)||parseInt(a._h,10)||parseInt(a.sh,10)||parseInt(b.rsi1,10),h=a.displayType,w=b.tn||"",G=w.toLowerCase(),n=b.ch||0,a=a.qn||"",s=b.n||"",t=b.dai||0;b.dtm="BAIDU_DUP2_SETJSONADSLOT";b.dc="2";b.di=j;var c=[],u;for(u in b)u&&b.hasOwnProperty(u)&&c.push(""+u+"="+encodeURIComponent(b[u].toString()));c=c.join("&");if((u=d.Na(b,h))&&u.serviceUrl!==k&&u.paramString!==k)i=u.serviceUrl,
c=u.paramString;return{slotId:j,slotWidth:f,slotHeight:g,displayType:h,styleType:G,unionAccount:s,adIndex:t,channel:n,pvId:a,stuffType:"unknown",serviceUrl:i,paramString:c,delayIn:b.delayIn,delayOut:b.delayOut,sessionSync:b.sessionSync!==q&&"false"!==b.sessionSync,closeFor:b.closeFor,xuantingType:b.xuanting,tn:w}},ra:function(a){var b={};b.ob=(a.ob||"pc").toLowerCase();b.k=(a.k||"inlay-fixed").toLowerCase();b.i=(a.i||"template_inlay_all_normal").toLowerCase();b.B=(a.B||"text").toLowerCase();if(-1<
b.i.indexOf("tlink")||-1<b.i.indexOf("linkunit"))b.k="linkunit-fixed";0<=b.i.indexOf("float_xuanfuwin")&&(b.k="popup-float");a=b.k.split("-");b.Q=a[0]||"inlay";b.Vb=a[1]||"fixed";return b},ca:function(a){a=this.ra(a);a=a.Q;return c[a]<h[a]},$b:function(a){a=this.ra(a);return c[a.Q]},ua:function(a){a=this.ra(a);c[a.Q]+=1;return l},Qa:function(a,b){var c=document.getElementById("cpro_"+a);c||(c=document.getElementById(b));return c},ub:function(a){return g[a]},mb:function(a){var b={"test.com":l,"people.com.cn":l,
"chinanews.com":l,"cri.cn":l,"chinadaily.com":l,"cnki.com.cn":l,"cnki.net":l,"ku6.com":l,"tgbus.com":l,"5068.com":l,"yzz.cn":l,"aipai.com":l,"stockstar.com":l},a=a||window,c="",d=a.document.domain.split("."),g=d.length;g&&2<g?c="cn"===d[g-1]&&"com"===d[g-2]?d[g-3]+"."+d[g-2]+"."+d[g-1]:d[g-2]+"."+d[g-1]:g&&(c=a.document.domain);return c&&b[c]?q:l}}});E&&E("union/xuanting","union/common/cookie1392089005,union/common/bom1392089005,union/common/dom1392089005,union/common/logic1392089005,union/common/oo1392089005,union/business/businessLogic1392089005".split(","),function(d,h,c,g,a,b){var e;a(function(a){e=a.Da({constructor:function(a){var b=a.L.id;this.L=c.e(a.L);this.type=+a.type;this.src=a.src;this.width=a.width;this.height=a.height;this.i=a.i||"";this.xa=a.xa||"";this.D=a.D||"0";this.K=a.K||"";this.sa=a.sa||"";this.M=this.za=5;this.l=a.l;this.v=a.v;this.m=a.m;this.ea="bd_close_"+this.m;this.Rb=!!d.T(this.ea);
this.b=this.yb(this.m);this.d=b;this.q="";this.fileName="c";this.N=a.N||0;2===this.type?this.q="top":3===this.type&&(this.q="bottom");this.q&&(this.gb=l,this.O=+a.O||0,this.P=+a.P||0,this.I=!!a.I||q,this.w=+a.w||0,this.hb=500);this.Va=a.Va||q},gc:function(a){return"string"===typeof a?document.getElementById(a):a},Lb:function(a,b){return(b||document).getElementsByTagName(a)[0]},eb:function(a,b){return a.replace(/\{(.*?)\}/g,function(a,j){return b.hasOwnProperty(j)?b[j]:a})},yb:function(a){var b={};
return function(){b.hasOwnProperty(a)||(b[a]=0);++b[a];return"cproIframe"+b[a]}}(),f:h.f,Jb:function(){var a={path:""};if(this.w&&!this.I){var b=new Date;b.setTime(b.getTime()+this.w);a.F=b}d.va(this.ea,1,a)},Hb:function(a){var b=new Date;b.setTime(b.getTime()-86400);d.va(a,"",{path:"/",F:b})},$:function(){this.clientWidth=h.ma(window);this.clientHeight=h.R(window);this.q&&(this.c&&(this.c.style.width=this.clientWidth+"px"),this.Aa&&(this.Aa.style.width=this.clientWidth+"px"));this.J&&clearTimeout(this.J);
this.J=setTimeout(a.h(this.qa,this),5)},qa:function(){var a=this.c;if(a)if(c.t()){if(a.style.zIndex=2147483646,1===this.type)if("fixed"==a.style.position)this.Fa(),this.ib()&&(a.style.cssText=p,this.Gb());else{var b=this.Ob();b&&(this.Ia(),a.style.position="fixed",a.style.top=b+"px",this.Fa())}}else this.Z(this.c)},ib:function(a){var b;a?(b=document.getElementById(a),a=document.getElementById(""+a+"placeholder")):(b=this.c||document.getElementById(this.d),a=document.getElementById(""+this.d+"placeholder"));
return b&&a&&(a=this.r(a).ba,this.r(b).ba<=a)?l:q},Fa:function(a){var b;a?(b=document.getElementById(a),a=document.getElementById(""+a+"placeholder")):(b=this.c||document.getElementById(this.d),a=document.getElementById(""+this.d+"placeholder"));b&&a&&(a=this.r(a).left,b.style.left=a+"px")},r:function(a){var b=c.S(a),e=h.Oa(window),i=h.U(window),d=c.Ab(a,q),a=c.zb(a,q);return{top:b.top-i,bottom:b.top-i+a,left:b.left-e,right:b.left-e+d,ba:b.top,Tb:b.top+a,X:b.left,mc:b.left+d}},Z:function(){this.clientWidth=
h.ma(window);this.clientHeight=h.R(window);var a=h.U(window),b=c.g(document.body,"position").toString(),e=c.S(document.body),i=e.left,d=e.top;if(e=this.c)if(e.style.position="absolute",e.style.zIndex=2147483646,1===this.type)if(document.getElementById(""+this.d+"placeholder")){var g=document.getElementById(""+this.d+"placeholder"),n=this.r(g);e.style.top=""+a+this.M+"px";e.style.left=""+n.X+"px";"relative"==b&&(e.style.top=a+this.M-d+"px",e.style.left=n.X-i+"px");e.style.visibility="visible";a=this.r(e);
n.ba>=a.ba&&(e.parentNode.removeChild(e),g.parentNode.insertBefore(e,g),g.parentNode.removeChild(g),e.style.cssText=p)}else{if(g=this.Pb(this.d))this.M=g,this.Ia(this.d),g=document.getElementById(""+this.d+"placeholder"),n=this.r(g),e.parentNode.removeChild(e),document.body.appendChild(e),e.style.zIndex=2147483646,e.style.top=a+this.M+"px",e.style.left=n.X+"px","relative"==b&&(e.style.top=a+this.M-d+"px",e.style.left=n.X-i+"px"),e.style.visibility="visible",e.style.position="absolute"}else 2===this.type?
e.style.top=a+"px":3===this.type&&(e.style.top=a+this.clientHeight-(this.height+10)+"px")},ta:function(){if(!this.Va){var a=this.type,b=this.width,e=this.height,i={srcAttrName:a===k||1==a?"src":"_src",iframeWidth:b,iframeHeight:e,iframeId:this.b,paramString:this.l||"",serviceUrl:this.v};this.Fb();var d=q;if(a&&(1===a||2===a||3===a)){var g=d="auto",h;if(1===a)h="inline-block",d=b+"px",g=e+"px";else if(2===a||3===a)h="block",d="100%",g=+e+10+"px";i.widthValue=d;i.heightValue=g;i.displayValue=h;a=this.L;
a.setAttribute("width",d);a.setAttribute("height",g);a.style.cssText=this.eb("width:{widthValue};height:{heightValue};display:{displayValue};",i);d=l}i=this.eb('<iframe id="{iframeId}" {srcAttrName}="{serviceUrl}{paramString}" width="{iframeWidth}" height="{iframeHeight}" align="center,center" marginwidth="0" marginheight="0" scrolling="no" frameborder="0" allowtransparency="true" ></iframe>',i);this.L.innerHTML=i;this.V=c.e(this.b);d&&(this.c=this.V.parentNode);this.nb();this.Qb()}},nb:function(){var a=
this.type,b=this.V,e=this.c;if(a){var i=1;if(2===a)i=2;else if(3===a)i=1;else if(1!==a&&0!==a&&this.c){this.c.style.display="none";return}var d=2===a||3===a,g="";switch(a){case 2:case 3:var g="display:none;",n="";this.f.a&&7>this.f.a&&(n="_background-image:none;_filter:progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+i+".png');");i=d?'<div id="'+this.b+'WrapToggle" style="z-index:2147483646;cursor:pointer;position:absolute;right:0;'+
this.q+':0;width:40px;height:100%;background-color:#3f3f3f;"><div style="width:20px;height:22px;position:absolute;top:50%;margin-top:-11px;left:50%;margin-left:-10px;background:no-repeat url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk'+i+".png);"+n+'"></div></div>':"";d=d?'<div id="'+this.b+'WrapBk" style="'+this.q+':0;left:0;position:absolute;width:100%;height:100%;background-color:#666;-moz-opacity:.6;filter:alpha(opacity=60);opacity:.6;"></div>':"";n="";c.t()?1===a?n="position:fixed;top:0;":
2===a?n="position:fixed;top:0;width:100%;":3===a&&(n="position:fixed;bottom:0;width:100%;"):1===a?n="position:absolute;top:0;":2===a?n="position:absolute;top:0;width:100%;":3===a&&(n="position:absolute;top:"+(h.U(window)+h.R(window)-this.width)+"px;width:100%;");e.insertAdjacentHTML("afterBegin",d+i);e.style.cssText=[g,"height:",this.height+10,"px;right:0;z-index:2147483646;text-align:center;font-size:0;_overflow-y:hidden;",n].join("");b.style.cssText="position:relative;margin:5px 0;";this.ya=c.e(""+
this.b+"WrapToggle");this.aa=this.Lb("DIV",this.ya);this.Aa=c.e(this.b+"WrapBk");this.$()}}},Ya:function(){var a=this.m,b=this.d,e=this;z(["viewWatch"],function(c){c.register({id:a,wrapperId:b,logType:"block",extra:"did="+e.N+"&ch="+e.D+"&jk="+e.sa+"&tn="+e.xa+"&n="+e.K+"&js="+e.fileName})},l)},Qb:function(){var b=this,e=b.c,d=b.type,g=b.V,b=this;this.q?this.Rb?e.parentNode.removeChild(e):(setTimeout(function(){e.style.display="block";if(2===d||3===d){var a=g.getAttribute("_src");a&&(g.setAttribute("src",
a),g.removeAttribute("_src"),b.Ya())}},this.O),this.P&&setTimeout(function(){e.style.display="none"},this.O+this.P)):this.Ya();this.ya&&(2===this.type||3===this.type)&&c.bind(this.ya,"click",a.h(this.Nb,this));c.bind(window,"scroll",a.h(this.qa,this));c.bind(window,"resize",a.h(this.qa,this))},Fb:function(){for(var a=1;2>=a;a++)(function(a){var b="bkimg_"+ +new Date+Math.floor(1E5*Math.random()),e=window[b]=new Image;e.onload=e.onerror=function(){e.onload=e.onerror=p;e=window[b]=p};e.src="http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk"+
a+".png"})(a)},Nb:function(){this.gb?this.Cb():this.show()},Xa:function(a){if(!this.Ga){this.Ga=l;var b=this.c,e=this.Aa,c=this.V,i=this.q,d=b.offsetHeight,g=Math.round(this.hb/d),h=0,t=this;a&&(b.style.width="100%");var u=+new Date,D=setInterval(function(){var b=h=Math.round((+new Date-u)/g),f=b;a&&(f=d-b);e.style[i]=-f+"px";c.style[i]=-f+"px";b>=d&&(t.Ga=q,(t.gb=a)&&"top"===i||!a&&"bottom"===i?t.f.a&&7>t.f.a?t.aa.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png');":
t.aa.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk2.png)":t.f.a&&7>t.f.a?t.aa.style.filter="progid:DXImageTransform.Microsoft.AlphaImageLoader(src='http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png');":t.aa.style.backgroundImage="url(http://cpro.baidustatic.com/cpro/ui/noexpire/img/toggle_btn_bk1.png)",f=d,a&&(f=0),e.style[i]=-f+"px",c.style[i]=-f+"px",clearInterval(D))},g)}},show:function(){(this.I||this.w)&&this.Hb(this.ea);this.Xa(l)},
Cb:function(){(this.I||this.w)&&this.Jb();this.Xa(q)},Ia:function(a){var b;a?(b=document.getElementById(a),a+="placeholder"):(b=this.c||document.getElementById(this.d),a=this.d+"placeholder");var e=document.createElement("div");e.id=a;e.align&&(e.align=b.getAttribute("align"));e.style.width=""+parseInt(b.getAttribute("width"),10)+"px";e.style.height=""+parseInt(b.getAttribute("height"),10)+"px";e.style.margin="0";e.style.padding="0";e.style.background="none";e.style.border="none";1===this.type&&(e.style.display=
"inline-block");b.parentNode.insertBefore(e,b);return l},Gb:function(a){a=document.getElementById(a?a+"placeholder":this.d+"placeholder");a.parentNode.removeChild(a);return l},Ob:function(a){var b=this.za;return this.r(a?document.getElementById(a):this.c||document.getElementById(this.d)).top<b?b:q},Pb:function(a){var b=this.za;return this.r(a?document.getElementById(a):this.c||document.getElementById(this.d)).top<b?b:q}})});return{render:function(a,c){switch(parseInt(a._html.xuanting,10)){case 1:a.displayType=
"inlay-float";break;case 2:a.displayType="float-top";break;case 3:a.displayType="float-bottom";break;default:a.displayType="inlay-float"}var d=b.Wa(a),g={k:d.displayType,i:d.styleType,B:d.stuffType};if(!b.ca(g))return q;(new e({L:b.Qa(d.slotId,c),m:d.slotId,type:d.xuantingType,src:"",width:d.slotWidth,height:d.slotHeight,i:d.styleType,xa:d.tn,D:d.channel,K:d.unionAccount,N:d.adIndex,sa:d.pvId,O:d.delayIn,P:d.delayOut,I:d.sessionSync,w:d.closeFor,l:d.paramString,v:d.serviceUrl})).ta();b.ua(g)}}});
})();
